# Generated by Django 4.0.3 on 2022-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyanalytics',
            name='end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
