# Generated by Django 4.0.5 on 2022-06-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='DeviceModel',
        ),
    ]
