# Generated by Django 4.0.5 on 2022-06-18 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyanalytics',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energyanalytics',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='energyanalytics',
            name='maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='energyanalytics',
            name='minimum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='energyanalytics',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
