# Generated by Django 4.0.3 on 2022-06-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_energyanalytics_end_alter_energyanalytics_average_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyconsumption',
            old_name='time',
            new_name='hour',
        ),
    ]
