# Generated by Django 4.0.5 on 2022-06-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_devicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='time',
            field=models.TimeField(),
        ),
    ]
