# Generated by Django 4.0.3 on 2022-06-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_time_energyconsumption_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='hour',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
