# Generated by Django 4.0.3 on 2022-06-17 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_requestdevice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdevice',
            old_name='is_approved',
            new_name='is_assigned',
        ),
        migrations.AddField(
            model_name='requestdevice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestdevice',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 17, 14, 57, 10, 492025, tzinfo=utc)),
        ),
    ]
