# Generated by Django 4.0.3 on 2022-06-17 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_approved_requestdevice_is_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdevice',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 17, 17, 52, 50, 356134, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='EnergyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.IntegerField(default=0, editable=False)),
                ('maximum', models.IntegerField(default=0, editable=False)),
                ('minimum', models.IntegerField(default=0, editable=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
