# Generated by Django 4.0.3 on 2022-06-17 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_requestdevice_date_energyanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdevice',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 17, 18, 11, 33, 826792, tzinfo=utc)),
        ),
    ]
