export { SignUpPage } from './Auth';
export { ConfirmEmailPage } from './ConfirmEmail'
export { SignInPage } from './Auth';
export { OverviewPage } from './dashboard';
export { Home } from './Home';
export { Contact } from './Contact';
export { GetStarted } from './GetStarted';
export { SolarInstallation } from './SolarInstallation'
export { SolarAnalytics } from './SolarAnalytics'
